### ISSUE TITLE
Automatically reconnect and resync state after disconnection

### ISSUE THREAD

**Issue by fbonetti** [mikemintz/react-rethinkdb#15]
First of all, I'd just like to thank you for putting together this package. I've been looking for something like this for a while - a way to keep the UI perfectly in sync with the database, without having to mess around with Flux and async HTTP calls to keep the data consistent. React and Rethinkdb are a perfect match for this.

One issue that I noticed when testing the chat example is that the client doesn't automatically reconnect after a disconnect. I was hoping that the client would reconnect and then bring itself up to speed, but I had to refresh the page in order to re-sync with DB. Is it possible to do this?

**Comment by mikemintz** [comment]
That's definitely an important feature we'll need, thank you for bringing it up. I don't have time to implement this now, but hopefully I will in the next week or two.

A naive implementation would modify [Session.connect()](https://github.com/mikemintz/react-rethinkdb/blob/709c07ca6a9c86eb2db11cc609b61a8749abdfd0/src/Session.js#L38-L45) and add this to the bottom:

```javascript
this._connPromise.then(conn => {
  conn.on('close', () => {
    console.warn('disconnected');
    setTimeout(() => {
      this._connPromise = null;
      this.connect({host, port, path, secure, db, simulatedLatencyMs});
    }, 1000);
  });
});
```

This code has some issues that will need to be addressed:

1. It's possible this will get triggered when the client explicitly calls `Session.close()`. We don't want to automatically reconnect when that happens.
2. Queries that are executed after disconnection and before the `setTimeout` finishes will immediately be rejected. Ideally we'd create a new promise first, and wait a delay before connecting, so that new queries will be resolved with the new connection.
3. We may want similar logic in a `this._connPromise.catch(...)` block so that we automatically reconnect if a connection attempt fails. In the code above, we only automatically reconnect if we are disconnected sometime after successfully initiating a connection, but ideally a user who visits the app while offline and gets online in a few seconds should automatically reconnect.
4. We'll want to make sure queries in component `observe()` functions work after reconnection. Queries with a changefeed will need to re-run, and queries without a changefeed will only need to rerun if we disconnected during the query execution. We'll probably want to populate `QueryResult.errors` until the query has successfully re-run.
5. Do we need to do anything special for queries that the client runs outside of `observe()`, like a create query triggered by a user pressing a button? For now, it's simplest to let the client developer handle the failed promise themselves, as opposed to automatically re-running the query until it completes or fails on a working connection.
6. How long should we wait before reconnecting? Should we use some sort of exponential back-off algorithm? What parameters should the client be able to customize, and what are sensible defaults? The client should certainly be able to disable it. Future extensions would allow hooking into connection information like cordova onDeviceReady or a react-native equivalent.

**Comment by mikemintz** [comment]
@fbonetti I just created a PR for auto reconnect. I didn't address point 5 (queries outside of observe) or point 6 (fancy delay algorithms).

If you want to try it out before I merge it and let me know if it works for your use case, that would be quite helpful. Here are instructions for using the version from my branch:

```
[~]$ git clone git@github.com:mikemintz/react-rethinkdb.git
[~]$ cd react-rethinkdb/
[~]$ git checkout auto-reconnect
[~]$ npm install
[~]$ cd ~/my-app
[~/my-app]$ rm -rf node_modules/react-rethinkdb
[~/my-app]$ ln -s ~/react-rethinkdb node_modules/react-rethinkdb
```

And when you want to go back to normal:
```
[~/my-app]$ rm -rf node_modules/react-rethinkdb
[~/my-app]$ npm install
```
