### ISSUE TITLE
Provide Installation Instructions

### ISSUE THREAD

**Issue by robtg4** [mikemintz/react-rethinkdb#9]
I know this is a novice issue but could you provide clear installation instructions into a react project? I would greatly appreciate that!

**Comment by mikemintz** [comment]
Hi @robtg4,

Are you using [npm](https://www.npmjs.com/) with something like [browserify](http://browserify.org/) or [webpack](http://webpack.github.io/) to manage dependencies? If so, all you should have to do is run:

```$ npm install react-rethinkdb --save```

And then you can copy the example code into your project from the ["how do I use this"](https://github.com/mikemintz/react-rethinkdb#how-do-i-use-this) section of the readme.

If that's still confusing, which step is confusing: getting the library installed, or getting the example to run, or both?

**Comment by robtg4** [comment]
Thanks for the quick response!

I think I was confused if I need to add the Web socket repo as well since
you mention using it within the description.

Also - what is the purpose of the observe function? Sorry for the novice
questions as I am still learning - I really appreciate your help and this
repo!

**Comment by mikemintz** [comment]
Oh that's a great point, react-rethinkdb is only for the client side, so you'd also need to set up a [rethinkdb-websocket-server](https://github.com/mikemintz/rethinkdb-websocket-server) to run on the server side. The projects in [`examples/`](https://github.com/mikemintz/react-rethinkdb/tree/master/examples) all illustrate that, so if you clone [`examples/chat/`](https://github.com/mikemintz/react-rethinkdb/tree/master/examples/chat) you can get something running quickly.

The observe function specifies the RethinkDB queries that a React component subscribes to. In the example in the readme, the `App` component subscribes to the `r.table('turtles')` query with the key `turtles`. That sets up the subscription, so that when `render()` is called, it has access to `this.data.turtles` which is a [`QueryResult`](https://github.com/mikemintz/react-rethinkdb/blob/master/src/QueryResult.js).

I think I should add a prominent "Get started" document, that explains all of the steps necessary to create a simple working app. Thanks for the feedback!

**Comment by mikemintz** [comment]
I just created a tutorial in #10, which I'll merge in soon. Let me know if this answers all of your questions for getting started, or if anything is still unclear.

**Comment by robtg4** [comment]
Thanks again!
